### ISSUE TITLE
As a user, I want to see a home page where I can log in or choose to sign up

### ISSUE THREAD

**Issue by gfdb** [gianfrancodumoulinbertucci/SOEN341#10]
Should contain login / sign up

**Child Issue for login**: https://github.com/gianfrancodumoulinbertucci/SOEN341/issues/11#issue-801666067 
**Child issue for signup**: https://github.com/gianfrancodumoulinbertucci/SOEN341/issues/12#issue-801669336
**Child issue for database**: https://github.com/gianfrancodumoulinbertucci/SOEN341/issues/13#issue-801669550

**Comment by gianfrancodumoulinbertucci** [comment]
Child Issue: https://github.com/gianfrancodumoulinbertucci/SOEN341/issues/11#issue-801666067
