### ISSUE TITLE
As a user, I want to see a login page when I open the website

### ISSUE THREAD

**Issue by gfdb** [gianfrancodumoulinbertucci/SOEN341#11]
### **BACKEND**
The login page should have a username/password form and a forgot password button. 

To do:

- Create the relevant functions in app.py that will render the templates created in the front-end ticket. 
- Create the `class LoginForm(FlaskForm)` that will accept an email `StringField` and a password `PasswordField`

Parent Story: https://github.com/gianfrancodumoulinbertucci/SOEN341/issues/10#issue-801664122

**Comment by david-roper** [comment]
Changed launching to a default timeline. Can login to account through navigation bar.
