### ISSUE TITLE
add basic templates to templates folder

### ISSUE THREAD

**Issue by gfdb** [gianfrancodumoulinbertucci/SOEN341#16]
Create the templates/static folders and add the basic html templates to templates.

Parent issue: https://github.com/gianfrancodumoulinbertucci/SOEN341/issues/17

**Comment by gianfrancodumoulinbertucci** [comment]
(Approved) [PR for this ticket](https://github.com/gianfrancodumoulinbertucci/SOEN341/pull/18)

**Comment by Omarelk09** [comment]
basic templates have been added
