### ISSUE TITLE
(EPIC) As a user, I want to see properly formatted website

### ISSUE THREAD

**Issue by david-roper** [gianfrancodumoulinbertucci/SOEN341#17]
As a user, I want to see a nice website. This means that when I open the website I will see a timeline page. On the timeline page I will be able to post a picture as well as see the pictures that other people have posted. 

Story for timeline page: https://github.com/gianfrancodumoulinbertucci/SOEN341/issues/9

**Comment by gfdb** [comment]
Being moved to Sprint 3, user functionality is yet to be implemented.
