### ISSUE TITLE
(Feature) As a user, I want to be able to post a picture

### ISSUE THREAD

**Issue by gfdb** [gianfrancodumoulinbertucci/SOEN341#20]
### **BACKEND**

- Once a picture is uploaded, it needs to be saved in the database with the written description
- After the picture is stored in the database, it needs to be displayed on the timeline page with the description

*New: adding user specific features for picture posting #39

**Comment by Cresfault** [comment]
Picture posting back-end is complete. Adding individual user information for each picture will be implemented when users are added.

**Comment by Cresfault** [comment]
Implementing for user specific features to picture posting

**Comment by Cresfault** [comment]
User specific features to picture posting have been added. Refer to #39 for more details
