### ISSUE TITLE
(Feature) As a user, I want to see a timeline page

### ISSUE THREAD

**Issue by gfdb** [gianfrancodumoulinbertucci/SOEN341#21]
#### Template for the timeline page needs to be created and should have the following:
- a navbar
- navbar should contain the `<a href = "/timeline">LOGO<a/>` on the top left and a "POST" button on the top right
- timeline page should have places for posted pictures to be displayed

**Comment by david-roper** [comment]
Accidental closure of issue

**Comment by gfdb** [comment]
issue resolved. pull request merged. https://github.com/gianfrancodumoulinbertucci/SOEN341/pull/30
