### ISSUE TITLE
(Story) As a user, I want to be able to post a picture

### ISSUE THREAD

**Issue by gfdb** [gianfrancodumoulinbertucci/SOEN341#23]
As a user, I want to be able to press on the post button located on the timeline page. This button should bring up a file explorer in which I can select and upload the picture I want to post. This picture should be saved in a database and then be displayed (from the database) on the timeline page along with all other pictures posted by other users.

frontend: https://github.com/gianfrancodumoulinbertucci/SOEN341/issues/19
backend: https://github.com/gianfrancodumoulinbertucci/SOEN341/issues/20

**Comment by Cresfault** [comment]
Database features to be implemented with newer features at a later date. JSON files serves in the place of the database for the time being.
