### ISSUE TITLE
(EPIC) As a user, I want to be able to comment on a picture

### ISSUE THREAD

**Issue by gfdb** [gianfrancodumoulinbertucci/SOEN341#24]
As a user, I want to be able to comment on a picture. There should be a comment box under each picture on my timeline. I should be able to click on the comment box, type in a message, and click post. My comment should be displayed under the picture along with all the other comments that have been posted on that picture. Any comments that have been commented on a picture should be saved in a database and displayed when that corresponding picture is loaded.

**Comment by gfdb** [comment]
Being moved to Sprint 3, user functionality is yet to be implemented.

**Comment by david-roper** [comment]
Users can now comment on pictures.
