### ISSUE TITLE
 (Feature) As a user, I want to be able to comment on a picture

### ISSUE THREAD

**Issue by gfdb** [gianfrancodumoulinbertucci/SOEN341#27]
### **BACKEND**

The back-end functionality for commenting on pictures requires the following:
- once comment is added from the UI, the comment needs to be stored in a database
- comment needs to be stored with some id that will link it to the picture
- relevant python code in app.py needs to be added for comment to be displayed.

**Comment by Omarelk09** [comment]
the user is now able to comment on a picture
