### ISSUE TITLE
(STORY) As a user, I want to have my own profile picture

### ISSUE THREAD

**Issue by mohamad-elchanati** [gianfrancodumoulinbertucci/SOEN341#49]
Users should have the ability to choose their own profile pics
#54 Having the ability to see the user profile picture frontend and back end
#55 Having the ability to change the user profile picture frontend and backend

**Comment by mohamad-elchanati** [comment]
#54 Having the ability to see the user profile picture frontend and back end
#55 Having the ability to change the user profile picture frontend and backend

**Comment by Omarelk09** [comment]
the user is able to have his own profile picture
