### ISSUE TITLE
(FEATURE) As a user, I should be able to like a post

### ISSUE THREAD

**Issue by gfdb** [gianfrancodumoulinbertucci/SOEN341#53]
STORY: https://github.com/gianfrancodumoulinbertucci/SOEN341/issues/52

As a user, I want to be able to click on some sort of "like" button and have my like be reflected on the post in some way. In contrast, if I no longer like the post, I should be able to unlike the post and have that be reflected as well.

**Comment by Omarelk09** [comment]
the user is able to like a post
