### ISSUE TITLE
(bugfix) removing the extra database

### ISSUE THREAD

**Issue by gfdb** [gianfrancodumoulinbertucci/SOEN341#63]
Right now there are two databases used for user accounts. The first database contains username, passwords, etc... (accounts.json) There is now a second database called profile_pic.json that needs to be combined with account.json. There should not be an extra database for new key, that key being "pic_URl". Also the key should not be half uppercase half lowercase. It should either be all uppercase or all lowercase and follow the snake case convention.

**Comment by Omarelk09** [comment]
eliminated redundancy in databases
