### ISSUE TITLE
(Story) As a user, I want to see a timeline page

### ISSUE THREAD

**Issue by gfdb** [gianfrancodumoulinbertucci/SOEN341#9]
Pictures posted by people that user is following should be displayed on user's homepage in reverse-chronological order.
- not sure how this will be implemented yet 

frontend: https://github.com/gianfrancodumoulinbertucci/SOEN341/issues/21
backend: https://github.com/gianfrancodumoulinbertucci/SOEN341/issues/22

**Comment by gfdb** [comment]
Being moved to Sprint 3, user functionality is yet to be implemented.

**Comment by david-roper** [comment]
Website now has a timeline page where users sees posts of people they follow.
